[package]
name = "cargo-limit"
version = "0.0.3"
authors = ["Alexander Lopatin <github.com/alopatindev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Cargo with less noise: warnings are skipped until errors are fixed, etc."
repository = "https://github.com/alopatindev/cargo-limit"
keywords = ["cargo", "limit", "filter", "wrapper", "dedup"]
readme = "README.md"

[dependencies]
anyhow = "1"
atty = "0.2"
cargo_metadata = "0.12"
const_format = "^0.2.8"
ctrlc = { version = "3", features = ["termination"] }
either = "1"
itertools = "0.9"
serde_json = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
